// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `from_str`, `try_from`

Future<(DateTime, DateTime, bool)> processRunner(
        {required TraceMode mode,
        required String name,
        required String executePath,
        required String monitorPath,
        required String workingDir,
        required int sleepCount,
        required Duration sleepDuration}) =>
    RustLib.instance.api.crateApiProcessRunnerProcessRunner(
        mode: mode,
        name: name,
        executePath: executePath,
        monitorPath: monitorPath,
        workingDir: workingDir,
        sleepCount: sleepCount,
        sleepDuration: sleepDuration);

/// trace mode
enum TraceMode {
  /// Wait child process to exit
  simple,

  /// Search process by given name and wait them all exit
  byName,
  ;
}
