name: dao
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dart_mappable: ^4.5.0
  drift: ^2.27.0
  drift_flutter: ^0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  dart_mappable_builder: ^4.5.0
  drift_dev: ^2.27.0
